version: "27.0.3"
services: 
  influxdb:
    image: influxdb2:2.7.8  # Updated to the specified version
    container_name: influxdb
    networks:
      - common_network
    ports:
      - "8086:8086"
    env_file:
      - influxdb.env
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - shared-data:/shared
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest  # Use the latest version available
    container_name: grafana
    networks:
      - common_network
    ports:
      - "3000:3000"
    env_file:
      - grafana.env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    restart: unless-stopped
  
  node-red:
    image: nodered/node-red:latest  # Use the latest version available
    container_name: node-red
    build:
      context: .
      dockerfile: "node-red/Dockerfile"
    ports:
      - "1880:1880"
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - "./node-red/data:/data"
    networks:
      - common_network
    environment: 
      - TZ=UTC+1
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest  # Use the latest version available
    container_name: mosquitto
    networks:
      - common_network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    env_file:
      - mosquitto.env
    restart: unless-stopped

networks:
  common_network:
    name: docker-influxdb-grafana-nodered-mqtt_common_network

volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:
  shared-data:
